// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
// 2026-04-28 (M16 階段 1)：對齊 ChildPanelBase 抽象 signature；內容待 B 路線階段 4 補完（寶：一般裝備 / 傳家寶 / 道具）。
// __ALIGN_NOTE__
//
// CharacterDs3EquipChild — UCUF ChildPanel for tab "Equip".
// Wire this into the CompositePanel's _switchToTab routing table.

import { ChildPanelBase } from '../../core/ChildPanelBase';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class CharacterDs3EquipChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabEquipContent';

    public override async onMount(_spec: Record<string, unknown>): Promise<void> {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[CharacterDs3EquipChild] onMount', { rootPath: CharacterDs3EquipChild.ROOT_PATH });
        // TODO(B-stage4): 一般裝備 / 傳家寶 / 道具槽。
    }

    public override onDataUpdate(_data: unknown): void {
        // TODO(B-stage4): 把 GeneralConfig.equipment / heirloom / inventory 映到槽位。
    }

    public override validateDataFormat(data: unknown): string | null {
        if (!data || typeof data !== 'object') {
            return 'CharacterDs3EquipChild expects a GeneralConfig-like object';
        }
        return null;
    }

    public override onUnmount(): void { /* no-op */ }
}
