// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
// 2026-04-28 (M16 階段 1)：對齊 ChildPanelBase 抽象 signature；內容待 B 路線階段 4 補完（屬：六色屬性條 / 教官評價）。

import { ChildPanelBase } from '../../core/ChildPanelBase';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class CharacterDs3StatsChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabStatsContent';

    public override async onMount(_spec: Record<string, unknown>): Promise<void> {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[CharacterDs3StatsChild] onMount', { rootPath: CharacterDs3StatsChild.ROOT_PATH });
        // TODO(B-stage4): cache Label / Sprite refs from binder under TabStatsContent (六色屬性條 / 教官評價)
    }

    public override onDataUpdate(_data: unknown): void {
        // TODO(B-stage4): 把 GeneralConfig.attributes / mentorEvaluation 映到屬性條。
    }

    public override validateDataFormat(data: unknown): string | null {
        if (!data || typeof data !== 'object') {
            return 'CharacterDs3StatsChild expects a GeneralConfig-like object';
        }
        return null;
    }

    public override onUnmount(): void { /* no-op */ }
}
