// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
// 2026-04-28 (M16 階段 1+2+3)：
//   - 對齊 ChildPanelBase 抽象 signature
//   - 改用 binder.getLabel(name) flat lookup（layout 已 rename 對應節點）
//   - rarity stars 用 container 子 Label 數量 toggle，避免破壞 5 顆星 layout
//
// 對應 layout 節點：
//   - TabOverviewContent       (container, 原 CharacterDs3Main_div_9)
//   - OverviewName             (label,    原 CharacterDs3Main_span_5)
//   - OverviewRoleBadge        (label,    原 CharacterDs3Main_div_13)
//   - OverviewRarityTier       (label,    原 CharacterDs3Main_span_7，"UR" 等)
//   - OverviewRarityStars      (container, 原 CharacterDs3Main_div_15，5 個 ★ 子 Label)

import { Label, Node } from 'cc';
import { ChildPanelBase } from '../../core/ChildPanelBase';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class CharacterDs3OverviewChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabOverviewContent';

    private _nameLabel:        Label | null = null;
    private _roleLabel:        Label | null = null;
    private _rarityTierLabel:  Label | null = null;
    private _rarityStarsRoot:  Node  | null = null;

    public override async onMount(_spec: Record<string, unknown>): Promise<void> {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[CharacterDs3OverviewChild] onMount', { rootPath: CharacterDs3OverviewChild.ROOT_PATH });
        this._nameLabel       = this.binder.getLabel('OverviewName');
        this._roleLabel       = this.binder.getLabel('OverviewRoleBadge');
        this._rarityTierLabel = this.binder.getLabel('OverviewRarityTier');
        this._rarityStarsRoot = this.binder.getNode('OverviewRarityStars');

        if (!this._nameLabel) {
            UCUFLogger.warn(LogCategory.LIFECYCLE,
                '[CharacterDs3OverviewChild] mount target missing — layout 未匯出 OverviewName，Overview 內容暫不渲染',
                { expected: 'OverviewName' });
        }
    }

    public override onDataUpdate(data: unknown): void {
        if (!data || typeof data !== 'object') return;
        const d = data as Record<string, unknown>;

        const setText = (label: Label | null, text: unknown): void => {
            if (label && typeof text === 'string' && text.length > 0) {
                label.string = text;
            }
        };

        setText(this._nameLabel, d.name);
        setText(this._roleLabel, d.roleArchetype);
        setText(this._rarityTierLabel, d.rarityLabel);

        if (this._rarityStarsRoot && typeof d.rarityTier === 'number') {
            const tier = Math.max(0, Math.min(7, d.rarityTier as number));
            const stars = this._rarityStarsRoot.children;
            for (let i = 0; i < stars.length; i++) {
                const star = stars[i];
                if (star) star.active = i < tier;
            }
        }
    }

    public override validateDataFormat(data: unknown): string | null {
        if (!data || typeof data !== 'object') {
            return 'CharacterDs3OverviewChild expects a GeneralConfig-like object';
        }
        return null;
    }

    public override onUnmount(): void {
        this._nameLabel       = null;
        this._roleLabel       = null;
        this._rarityTierLabel = null;
        this._rarityStarsRoot = null;
    }
}
