// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
// 2026-04-28 (M16 階段 1)：對齊 ChildPanelBase 抽象 signature；內容待 B 路線階段 4 補完（兵：戰場適性 + 虎符槽）。
// __ALIGN_NOTE__
//
// CharacterDs3AptitudeChild — UCUF ChildPanel for tab "Aptitude".
// Wire this into the CompositePanel's _switchToTab routing table.

import { ChildPanelBase } from '../../core/ChildPanelBase';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class CharacterDs3AptitudeChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabAptitudeContent';

    public override async onMount(_spec: Record<string, unknown>): Promise<void> {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[CharacterDs3AptitudeChild] onMount', { rootPath: CharacterDs3AptitudeChild.ROOT_PATH });
        // TODO(B-stage4): 戰場適性條 / 虎符槽。
    }

    public override onDataUpdate(_data: unknown): void {
        // TODO(B-stage4): 把 GeneralConfig.aptitude / tigerTallySlots 映到槽位。
    }

    public override validateDataFormat(data: unknown): string | null {
        if (!data || typeof data !== 'object') {
            return 'CharacterDs3AptitudeChild expects a GeneralConfig-like object';
        }
        return null;
    }

    public override onUnmount(): void { /* no-op */ }
}
