// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
// 2026-04-28 (M16 階段 1)：對齊 ChildPanelBase 抽象 signature；內容待 B 路線階段 4 補完（命：14 人祖先血統圖 + 命槽）。
// __ALIGN_NOTE__
//
// CharacterDs3BloodlineChild — UCUF ChildPanel for tab "Bloodline".
// Wire this into the CompositePanel's _switchToTab routing table.

import { ChildPanelBase } from '../../core/ChildPanelBase';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class CharacterDs3BloodlineChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabBloodlineContent';

    public override async onMount(_spec: Record<string, unknown>): Promise<void> {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[CharacterDs3BloodlineChild] onMount', { rootPath: CharacterDs3BloodlineChild.ROOT_PATH });
        // TODO(B-stage4): 背景血統圖 14 人 + 英靈卡命槽。
    }

    public override onDataUpdate(_data: unknown): void {
        // TODO(B-stage4): 把 GeneralConfig.bloodline / spiritCardSlots 映到視覺。
    }

    public override validateDataFormat(data: unknown): string | null {
        if (!data || typeof data !== 'object') {
            return 'CharacterDs3BloodlineChild expects a GeneralConfig-like object';
        }
        return null;
    }

    public override onUnmount(): void { /* no-op */ }
}
