// doc_id: doc_other_0009 — generated by generate-tab-childpanels.js (M33)
// 2026-04-28 (M16 階段 1)：對齊 ChildPanelBase 抽象 signature；內容待 B 路線階段 4 補完（技：戰法習得清單）。

import { ChildPanelBase } from '../../core/ChildPanelBase';
import { UCUFLogger, LogCategory } from '../../core/UCUFLogger';

export class CharacterDs3TacticsChild extends ChildPanelBase {
    override dataSource = 'config';
    private static readonly ROOT_PATH = 'TabTacticsContent';

    public override async onMount(_spec: Record<string, unknown>): Promise<void> {
        UCUFLogger.info(LogCategory.LIFECYCLE, '[CharacterDs3TacticsChild] onMount', { rootPath: CharacterDs3TacticsChild.ROOT_PATH });
        // TODO(B-stage4): cache Label / Sprite refs from binder under TabTacticsContent (戰法習得清單)
    }

    public override onDataUpdate(_data: unknown): void {
        // TODO(B-stage4): 把 GeneralConfig.tactics 映到清單列。
    }

    public override validateDataFormat(data: unknown): string | null {
        if (!data || typeof data !== 'object') {
            return 'CharacterDs3TacticsChild expects a GeneralConfig-like object';
        }
        return null;
    }

    public override onUnmount(): void { /* no-op */ }
}
